gnn_layers: 2
in_dim: 384
hidden_dim: 768
dropout: 0.1
head: 8
dropedge: 0
nag_agg: add
hops: 3
ckpt_dir: ./ckpt-2
ckpt_name: lp
pretrain_epoch: 9
score_input: edge
num_experts: 4
temperature: 1.0
task: lp
align: true
merge_method: logit
use_gate_proj: false
use_gate_mlp: false
use_hard_sample: true
cluster_init_method: normal
eval_batch_size: 20000 